### ISSUE TITLE
Seems like settings don't "stick"

### ISSUE THREAD

**Issue by jlmcgehee21** [nicholasrobinson/node-smartcielo-http#2]
When running the server, and trying to control my unit, I get the following.

```
$ curl http://localhost:6969/temperature/65
{"success":true}

$ curl http://localhost:6969/temperature
{"temperature":75}
```
My system is a Mr. Cool with firmware version 2.4.0

Do you know why that could be?

**Comment by nicholasrobinson** [comment]
This is most likely the same issue reported in the homebridge implementation:
https://github.com/nicholasrobinson/homebridge-smartcielo/issues/6

Which is likely due to invalid payload being generated by the underlying driver:
https://github.com/nicholasrobinson/node-smartcielo

to investigate further I would advise you follow the debugging steps outlined here:
https://github.com/nicholasrobinson/homebridge-smartcielo/issues/6#issuecomment-754276255

**Comment by nicholasrobinson** [comment]
Closing per https://github.com/nicholasrobinson/node-smartcielo-http/issues/5
